-- /****
--   * 
--   * CLIENTES POR BASE DE DATOS, RUT E IDCLIENTE
--   * 
--   * COLUMNAS
--   * [0] db
--   * [1] idContenedor
--   * [2] rutProveedor
--   * [3] cantidad
--   * 
-- ****/
-- select top 3 'Golden'			BD, concat(try_cast(left(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), 1))) Rut, c.IDCliente from [Mant_Golden_20180327].[dbo].[Clientefontana]			c where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and try_cast(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and c.Pais = 'CL' and len(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 union
-- select top 3 'Internacional'  BD, concat(try_cast(left(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), 1))) Rut, c.IDCliente from [Mant_Internacional_20180327].[dbo].[Clientefontana]	c where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and try_cast(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and c.Pais = 'CL' and len(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 union
-- select top 3 'Platinum'	    BD, concat(try_cast(left(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), 1))) Rut, c.IDCliente from [Mant_Platinum_20180220].[dbo].[Clientefontana]		c where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and try_cast(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and c.Pais = 'CL' and len(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 union
-- select top 3 'Pyme'   		BD, concat(try_cast(left(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), 1))) Rut, c.IDCliente from [Mant_Pyme_20180326].[dbo].[Clientefontana]			c where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and try_cast(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and c.Pais = 'CL' and len(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 union
-- select top 3 'Silver'         BD, concat(try_cast(left(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), 1))) Rut, c.IDCliente from [Mant_Silver_20180327].[dbo].[Clientefontana]			c where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and try_cast(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and c.Pais = 'CL' and len(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 union
-- select top 3 'Trial'			BD, concat(try_cast(left(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''), 1))) Rut, c.IDCliente from [Trial_20171020].[dbo].[Clientefontana]				c where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and try_cast(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and c.Pais = 'CL' and len(replace(replace(replace(replace(c.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2

-- /****
--   * 
--   * PROVEEDORES POR BASE DE DATOS Y CONTENEDOR
--   * 
--   * COLUMNAS
--   * [0] db
--   * [1] idContenedor
--   * [2] rutProveedor
--   * [3] cantidad
--   * 
-- ****/
-- select 'Golden'			db, pc.idContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [Mant_Golden_20180327].[dbo].[Clientefontana]			c inner join [Mant_Golden_20180327].[dbo].[Empresa]			e on c.idcliente = e.idcliente inner join [Mant_Golden_20180327].[dbo].[Ficha]			f on e.idempresa = f.idempresa inner join [Gestion_Clientes2].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by pc.IDContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union
-- select 'Internacional'	db, pc.idContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [Mant_Internacional_20180327].[dbo].[Clientefontana]	c inner join [Mant_Internacional_20180327].[dbo].[Empresa]	e on c.idcliente = e.idcliente inner join [Mant_Internacional_20180327].[dbo].[Ficha]	f on e.idempresa = f.idempresa inner join [Gestion_Clientes2].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by pc.IDContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union
-- select 'Platinum'		db, pc.idContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [Mant_Platinum_20180220].[dbo].[Clientefontana]		c inner join [Mant_Platinum_20180220].[dbo].[Empresa]		e on c.idcliente = e.idcliente inner join [Mant_Platinum_20180220].[dbo].[Ficha]		f on e.idempresa = f.idempresa inner join [Gestion_Clientes2].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by pc.IDContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union
-- select 'Pyme'			db, pc.idContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [Mant_Pyme_20180326].[dbo].[Clientefontana]			c inner join [Mant_Pyme_20180326].[dbo].[Empresa]			e on c.idcliente = e.idcliente inner join [Mant_Pyme_20180326].[dbo].[Ficha]			f on e.idempresa = f.idempresa inner join [Gestion_Clientes2].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by pc.IDContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union
-- select 'Silver'			db, pc.idContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [Mant_Silver_20180327].[dbo].[Clientefontana]			c inner join [Mant_Silver_20180327].[dbo].[Empresa]			e on c.idcliente = e.idcliente inner join [Mant_Silver_20180327].[dbo].[Ficha]			f on e.idempresa = f.idempresa inner join [Gestion_Clientes2].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by pc.IDContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union
-- select 'Trial'			db, pc.idContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [Trial_20171020].[dbo].[Clientefontana]				c inner join [Trial_20171020].[dbo].[Empresa]				e on c.idcliente = e.idcliente inner join [Trial_20171020].[dbo].[Ficha]				f on e.idempresa = f.idempresa inner join [Gestion_Clientes2].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by pc.IDContenedor, concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1)))


/****
  * 
  * RUT DE PROVEEDORES Y CANTIDAD, E INFORMACION DEL SII
  * 
  * COLUMNAS
  * [0] [rutProveedor]
  * [1] [cantidad]
  * [2] [Tramo Ventas]
  * [3] [Numero Trabajadores]
  * [4] [Rubro]
  * [5] [Subrubro]
  * [6] [Actividad Economica]
  * [7] [Region]
  * [8] [Comuna]
  * [9] [Calle]
  * [10] [Numero]
  * [11] [Bloque]
  * [12] [Villa/Poblacion]
  * [13] [Fecha Inicio]
  * [14] [Fecha Termino Giro]
  * [15] [Tipo Termino Giro]
  * [16] [Tipo Contribuyente]
  * [17] [SubTipoContribuyente]
  * [18] [F22 C 645]
  * [19] [F22 C 646]
  * 
****/
select 
	r.rutProveedor, sum(r.cantidad) cantidad, 
	ce.[Tramo Ventas], ce.[Numero Trabajadores], ce.Rubro, ce.Subrubro, ce.[Actividad Economica], ce.Region, ce.Comuna, ce.Calle, ce.Numero, ce.Bloque, ce.[Villa/Poblacion], ce.[Fecha Inicio], ce.[Fecha Termino Giro], ce.[Tipo Termino Giro], ce.[Tipo Contribuyente], ce.SubTipoContribuyente, ce.[F22 C 645], ce.[F22 C 646],
	csii.FechaResolucion, csii.NumResolucion, csii.MailIntercambio
from (
	select concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [Pyme].[dbo].[Clientefontana]						c inner join [Pyme].[dbo].[Empresa]							e on c.idcliente = e.idcliente inner join [Pyme].[dbo].[Ficha]							f on e.idempresa = f.idempresa inner join [Gestion_Clientes].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union all
	select concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [10.0.0.236].[Ssilver].[dbo].[Clientefontana]		c inner join [10.0.0.236].[Ssilver].[dbo].[Empresa]			e on c.idcliente = e.idcliente inner join [10.0.0.236].[Ssilver].[dbo].[Ficha]			f on e.idempresa = f.idempresa inner join [Gestion_Clientes].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union all
	select concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [10.0.0.236].[Golden].[dbo].[Clientefontana]		c inner join [10.0.0.236].[Golden].[dbo].[Empresa]			e on c.idcliente = e.idcliente inner join [10.0.0.236].[Golden].[dbo].[Ficha]			f on e.idempresa = f.idempresa inner join [Gestion_Clientes].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union all
	select concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [10.0.0.236].[Platinum].[dbo].[Clientefontana]		c inner join [10.0.0.236].[Platinum].[dbo].[Empresa]		e on c.idcliente = e.idcliente inner join [10.0.0.236].[Platinum].[dbo].[Ficha]			f on e.idempresa = f.idempresa inner join [Gestion_Clientes].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union all
	select concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [10.0.0.236].[Internacional].[dbo].[Clientefontana]	c inner join [10.0.0.236].[Internacional].[dbo].[Empresa]	e on c.idcliente = e.idcliente inner join [10.0.0.236].[Internacional].[dbo].[Ficha]	f on e.idempresa = f.idempresa inner join [Gestion_Clientes].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) union all
	select concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1))) rutProveedor, count(*) cantidad from [10.0.0.236].[Trial].[dbo].[Clientefontana]			c inner join [10.0.0.236].[Trial].[dbo].[Empresa]			e on c.idcliente = e.idcliente inner join [10.0.0.236].[Trial].[dbo].[Ficha]			f on e.idempresa = f.idempresa inner join [Gestion_Clientes].[dbo].[PlanesComerciales] pc on c.idplan = pc.IDPlan where c.tipocliente <> 'D' and c.fechaexpiracion > getdate() and c.condicion = 'S' and c.Pais = 'CL' and try_cast(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','') as numeric) is not null and len(replace(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''),'K','')) >= 2 and f.Proveedor = 'S' group by concat(try_cast(left(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), len(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ','')) - 1) as numeric), '-', upper(right(replace(replace(replace(f.CodLegal, '.',''),'-',''),' ',''), 1)))
) r
left join crm.dbo.CRM_EmpresasSII ce on r.rutProveedor = concat(ce.RUT,'-',ce.dv)
left join [10.0.0.167].[Felect].[dbo].[ContribuyenteSII] csii on r.rutProveedor = csii.codlegal collate SQL_Latin1_General_CP1_CI_AS
group by
	r.rutProveedor,
	ce.[Tramo Ventas], ce.[Numero Trabajadores], ce.Rubro, ce.Subrubro, ce.[Actividad Economica], ce.Region, ce.Comuna, ce.Calle, ce.Numero, ce.Bloque, ce.[Villa/Poblacion], ce.[Fecha Inicio], ce.[Fecha Termino Giro], ce.[Tipo Termino Giro], ce.[Tipo Contribuyente], ce.SubTipoContribuyente, ce.[F22 C 645], ce.[F22 C 646],
	csii.FechaResolucion, csii.NumResolucion, csii.MailIntercambio
